<?php

/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace app\assets;

use yii\web\AssetBundle;

/**
 * Main application asset bundle.
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
class WorkbenchAsset extends AssetBundle
{

    public $basePath = '@webroot';
    public $baseUrl = '@web/ai-parser/AttributeParser-X-Balloon/';
    public $css = [
        'node_modules/@fortawesome/fontawesome-free/css/all.min.css',
        "node_modules/bootstrap/dist/css/bootstrap.min.css",
        "node_modules/bootstrap-select/dist/css/bootstrap-select.min.css",
        "css/main.css",
        "css/tabs.css",
        "css/loading.css"
    ];


    public $js = [
        "node_modules/jquery/dist/jquery.min.js",
        "node_modules/popper.js/dist/umd/popper.min.js",
        "node_modules/bootstrap/dist/js/bootstrap.min.js",
        "node_modules/bootstrap-select/dist/js/bootstrap-select.min.js",
        "node_modules/konva/konva.min.js",
        "node_modules/moment/min/moment-with-locales.min.js",

        //  my libs
//        generics
        'js/Generic/KonvaFEvent.js',
        'js/Generic/ObjectHandlingContext.js',
        'js/Generic/Context.js',
        'js/Generic/Modal.js',
        'js/Generic/ContextEvent.js',
        'js/Generic/KonvaShapeF.js',
        'js/Generic/Shape.js',
        'js/Generic/Tab.js',
        'js/Generic/UrlConnection.js',
        'js/Generic/Toast.js',
        'js/Generic/UI.js',
        'js/Generic/Model.js',
        "js/UI/TabUI.js",
        "js/UI/TabHandlerUI.js",
        //tabs
        'js/Tab/AllTabsUI.js',
        'js/Tab/ClassificationTabUI.js',
        'js/Tab/ShapeTabUI.js',
        'js/Tab/ZoomTabUI.js',
        'js/Tab/SelectImageTabUI.js',
        'js/Tab/SettingTabUI.js',
        'js/Tab/JobsTabUI.js',
        "js/Tab/RegionAttributesTabUI.js",
        //shapes
        'js/Shape/Circle.js',
        'js/Shape/Line.js',
        'js/Shape/Polygon.js',
        'js/Shape/Ellipse.js',
        'js/Shape/Rectangle.js',
        'js/Shape/MultiPolygon.js',
        //instances
        'js/Instance/Helper.js',
        'js/Instance/Translation.js',
        'js/Instance/CollectDataShapes.js',
        'js/Instance/Runtime.js',
        'js/Instance/ImageLoaded.js',
        'js/Instance/JobsToDo.js',
        //services
        'js/Service/SaveShapesService.js',
        'js/Service/ReceiveImageService.js',
        'js/Service/UploadImageService.js',
        'js/Service/ReceiveShapesPerImageService.js',
        'js/Service/ReceiveAllEssentialsService.js',
        'js/Service/ReceiveImageStatisticsService.js',
        'js/Service/SetUserConfigurationService.js',
        //models
        'js/Models/ModelShape.js',
        'js/Models/ClassificationModel.js',
        'js/Models/ShapeType.js',
        'js/Models/ImageModel.js',
        'js/Models/UserConfiguration.js',
        'js/Models/User.js',
        //master
        'js/Generic/Master.js'

    ];


    function get_current_git_commit($branch = 'master')
    {

        try {


            if ($hash = file_get_contents(sprintf('../.git/modules/web/ai-parser/AttributeParser-X-Balloon/refs/heads/%s', $branch))) {
                return trim($hash);
            } else {
                return "1";
            }
        } catch (\Exception $exception) {
            return "1";
        }
    }

    public function init()
    {
        foreach ($this->css as $key => $css)
            $this->css[$key] = $css . "?v=" . $this->get_current_git_commit();
        foreach ($this->js as $key => $js)
            $this->js[$key] = $js . "?v=" . $this->get_current_git_commit();


        parent::init(); // TODO: Change the autogenerated stub
    }

    public $depends = [
        //'yii\web\YiiAsset',
        //'yii\bootstrap4\BootstrapAsset',
    ];

}
